# Analiza podatkov

Podatki so zbrani iz spletne strani [AMZS](https://www.amzs.si/na-poti/Potovalne-informacije-po-evropskih-drzavah).

Dodatne informacije o projektu in navodila najdete v [README.md](https://github.com/PinoPavlin/CeneKazniEvropskihDrzav/blob/main/README.md).

## Priprava knjižnic in osnovnih nastavitev

Najprej uvozimo programa [tabela_csv.py](https://github.com/PinoPavlin/PrviRepozitorij/blob/main/tabela_csv.py) in [pretvori_v_EUR.py](https://github.com/PinoPavlin/PrviRepozitorij/blob/main/pretvori_v_EUR.py), s katerima dobimo dostop tudi do glavnega programa [pridobi_podatke_podstrani.py](https://github.com/PinoPavlin/PrviRepozitorij/blob/main/pridobi_podatke_podstrani.py), ki iz [spletne strani](https://www.amzs.si/na-poti/Potovalne-informacije-po-evropskih-drzavah) pobere podatke za vse evropske države.

In [4]:
from tabela_csv import *
from pretvori_v_EUR import *

## Pridobivanje podatkov za posamezno državo

Spodnja tabela prikaže podatke o valuti in cenah štirih različnih kazni za poljubno evropsko državo.

Te kazni so:
- **Vožnja pod vplivom alkohola**           (v tabeli označeno kot alkohol)
- **Prehitra vožnja v naselju za 20 km/h**  (v tabeli označeno kot voznja)
- **Neuporaba varnostnega pasu**            (v tabeli označeno kot pas)
- **Uporaba mobilnega telefona**            (v tabeli označeno kot telefon)

V našem primeru so prikazani podatki za Slovenijo.

In [9]:
import pandas as pd

testna_drzava = "slovenija"
slovar = pridobi_kazni_za_drzavo(testna_drzava)
df = pd.DataFrame(list(slovar.items()), columns=["",""], index=["","","","","",""])
df

drzava      Slovenija
   valuta            EUR
  alkohol    300 - 1.200
   voznja  120 + 3 točke
      pas            120
  telefon  250 + 3 točke

## Analiza osnovne .csv datoteke

V spodnji tabeli so prikazani podatki za **vse** evropske države.

_Ker pa v nekaterih državah ne uporabljajo valute EUR, je za lažjo predstavo potrebno poskrbeti tudi za to (v nadaljevanju)._

In [12]:
tabela = pd.read_csv("kazni_evropske_drzave.csv")
tabela

Država Valuta               Kazni za alkohol  \
0             Albanija    ALL                 5.000 - 15.000   
1               Andora    EUR                         do 600   
2             Avstrija    EUR                    300 - 5.900   
3              Belgija    EUR                   150 - 16.000   
4           Belorusija    BYN                  1.225 - 2.450   
5                  BIH    BAM                      50 - 1000   
6            Bolgarija    BGN                     500 - 1000   
7                Češka    CZK                 2.500 - 50.000   
8            Črna Gora    EUR                     70 - 2.000   
9               Danska    DKK   na podlagi mesečnega dohodka   
10            Estonija    EUR                    400 - 1.200   
11              Finska    EUR                   dnevne kazni   
12            Francija    EUR                    135 - 4.500   
13           Gibraltar    GBP                            NaN   
14              Grčija    EUR                     78 - 1.200   
15             Hrvaška    EUR   90 - 2.650 ali zaporna kazen   
16               Irska    EUR                       do 5.000   
17           Islandija    ISK               70.000 - 160.000   
18             Italija    EUR                    532 - 6.000   
19              Kosovo    EUR                       65 - 130   
20             Latvija    EUR                    210 - 1.400   
21       Liechtenstein    CHF                    600 - 5.000   
22               Litva    EUR                    289 - 1.400   
23          Luksemburg    EUR                   145 - 10.000   
24           Madžarska    HUF              100.000 - 200.000   
25               Malta    EUR                  1.200 - 2.329   
26           Moldavija    MDL                 7.500 - 25.000   
27              Monako    EUR                    200 - 9.000   
28             Nemčija    EUR                    500 - 1.500   
29          Nizozemska    EUR                      300 - 650   
30            Norveška    NOK                   6.500–11.000   
31             Poljska    PLN                       do 5.000   
32         Portugalska    EUR                    250 - 2.500   
33            Romunija    RON                  1.305 - 2.900   
34              Rusija    RUB                 5.000 - 30.000   
35  Severna Makedonija    MKD                15.300 - 24.600   
36            Slovaška    EUR                    200 - 1.000   
37           Slovenija    EUR                    300 - 1.200   
38             Španija    EUR                    500 - 1.000   
39              Srbija    RSD                5.000 - 120.000   
40             Švedska    SEK  odvisno od mesečnega prihodka   
41               Švica    CHF                    600 - 6.500   
42             Turčija    TRY                    1002 - 2869   
43            Ukrajina    UAH                  2.550 - 3.400   
44        V. Britanija    GBP                          5.000   

   Kazni za prehitro vožnjo   Kazni za varnostni pas Kazni za mobilni telefon  
0             2.000 - 6.000                    5.000                    5.000  
1                        24  20 na neprivezano osebo                      NaN  
2                  35 - 726                  35 - 72                  50 - 72  
3                       160                      116                      116  
4                      24,5                     24,5                       49  
5                        50                100 - 300                100 - 300  
6                  20 - 600                       50                       50  
7             2.500 - 5.000            1.500 - 2.500            1.500 - 2.500  
8                  60 - 150                 40 - 100                 60 - 150  
9                     3.500                    1.500                    1.500  
10                      120                200 - 400                200 - 400  
11                      200                       70                      100  
12                      135    

## Analiza .csv datoteke z minimalnimi cenami kazni

Kot je razvidno iz zgornje (osnovne) tabele, niso vse cene fiksne (npr. "5.000 - 15.000"), nekatere so celo ubesedene (npr. "na podlagi mesečnega dohodka").

To sem rešil tako, da sem za vsako državo vzel zgolj minimalno ceno kazni, za države z ubesedeno kaznijo ali pa so brez podatka sem napisal ceno 0. (**Glej** [**Opozorila 1 in 2**](https://github.com/PinoPavlin/CeneKazniEvropskihDrzav/tree/main?tab=readme-ov-file#opozorila-) **v** [**README.md**](https://github.com/PinoPavlin/CeneKazniEvropskihDrzav/blob/main/README.md))

To predstavlja spodnja tabela:

In [14]:
minimum_tabela = pd.read_csv("kazni_evropske_drzave_minimum.csv")
minimum_tabela

Država Valuta Min kazni za alkohol  \
0             Albanija    ALL                5.000   
1               Andora    EUR                  600   
2             Avstrija    EUR                 300    
3              Belgija    EUR                 150    
4           Belorusija    BYN                1.225   
5                  BIH    BAM                  50    
6            Bolgarija    BGN                 500    
7                Češka    CZK                2.500   
8            Črna Gora    EUR                  70    
9               Danska    DKK                    0   
10            Estonija    EUR                 400    
11              Finska    EUR                    0   
12            Francija    EUR                 135    
13           Gibraltar    GBP                    0   
14              Grčija    EUR                  78    
15             Hrvaška    EUR                  90    
16               Irska    EUR                5.000   
17           Islandija    ISK               70.000   
18             Italija    EUR                 532    
19              Kosovo    EUR                  65    
20             Latvija    EUR                 210    
21       Liechtenstein    CHF                 600    
22               Litva    EUR                 289    
23          Luksemburg    EUR                 145    
24           Madžarska    HUF              100.000   
25               Malta    EUR                1.200   
26           Moldavija    MDL                7.500   
27              Monako    EUR                 200    
28             Nemčija    EUR                 500    
29          Nizozemska    EUR                 300    
30            Norveška    NOK                6.500   
31             Poljska    PLN                5.000   
32         Portugalska    EUR                 250    
33            Romunija    RON                1.305   
34              Rusija    RUB                5.000   
35  Severna Makedonija    MKD               15.300   
36            Slovaška    EUR                 200    
37           Slovenija    EUR                 300    
38             Španija    EUR                 500    
39              Srbija    RSD                5.000   
40             Švedska    SEK                    0   
41               Švica    CHF                 600    
42             Turčija    TRY                1002    
43            Ukrajina    UAH                2.550   
44        V. Britanija    GBP                5.000   

   Min kazni za prehitro vožnjo Min kazni za varnostni pas  \
0                         2.000                      5.000   
1                            24                        20    
2                           35                         35    
3                           160                        116   
4                          24,5                       24,5   
5                            50                       100    
6                           20                          50   
7                         2.500                      1.500   
8                           60                         40    
9                         3.500                      1.500   
10                          120                       200    
11                          200                         70   
12                          135                        135   
13                            0                          0   
14                          100                        350   
15                          130                        130   
16                          160                        120   
17                       15.000                     10.000   
18                         169                         80    
19                           35                         35   
20                           40                         30   
21                         180                          60   
22                          30                         30    
23                          145            

## Funkcija za pretvorbo kazni v EUR

Vemo, da določene evropske države nimajo EUR za valuto, zato je za lažjo predstavo in uporabo dobro pretvoriti ceno v EUR. To naredi spodnja celica.

In [ ]:
testna_cena = "100"
testna_valuta = "HUF"
pretvorjena_cena = pretvori_v_eur(testna_cena, testna_valuta)
f"Pretvorjena cena: {pretvorjena_cena} EUR"

'Pretvorjena cena: 0.2 EUR'

## Analiza .csv datoteke s pretvorjenimi cenami v EUR

Podatki v [kazni_evropske_drzave_minimum.csv](https://github.com/PinoPavlin/PrviRepozitorij/blob/main/kazni_evropske_drzave_minimum.csv) so dokaj neuporabni, saj verjetno ne poznamo pretvorb za vse valute v EUR.

V ta namen spodnja tabela prikazuje minimalne cene vseh kazni za evropske države v EUR.

Glej [**Opozorilo 7**](https://github.com/PinoPavlin/CeneKazniEvropskihDrzav/tree/main#:~:text=V%20datotekah%20kazni_evropske_drzave_eur.csv%20in%20kazni_evropske_drzave_eur_sortirano.csv%20je%20kljub%20pretvorbi%20v%20EUR%20%C5%A1e%20vedno%20zapisana%20mati%C4%8Dna%20valuta%20dr%C5%BEave.) za zapis valute v tabeli!

In [13]:
pretvorjeno_tabela = pd.read_csv("kazni_evropske_drzave_eur.csv")
pretvorjeno_tabela

Država Valuta  Min kazni za alkohol (EUR)  \
0             Albanija    ALL                       50.00   
1               Andora    EUR                      600.00   
2             Avstrija    EUR                      300.00   
3              Belgija    EUR                      150.00   
4           Belorusija    BYN                      344.23   
5                  BIH    BAM                       25.55   
6            Bolgarija    BGN                      255.50   
7                Češka    CZK                       97.50   
8            Črna Gora    EUR                       70.00   
9               Danska    DKK                        0.00   
10            Estonija    EUR                      400.00   
11              Finska    EUR                        0.00   
12            Francija    EUR                      135.00   
13           Gibraltar    GBP                        0.00   
14              Grčija    EUR                       78.00   
15             Hrvaška    EUR                       90.00   
16               Irska    EUR                     5000.00   
17           Islandija    ISK                      490.00   
18             Italija    EUR                      532.00   
19              Kosovo    EUR                       65.00   
20             Latvija    EUR                      210.00   
21       Liechtenstein    CHF                      640.20   
22               Litva    EUR                      289.00   
23          Luksemburg    EUR                      145.00   
24           Madžarska    HUF                      200.00   
25               Malta    EUR                     1200.00   
26           Moldavija    MDL                      390.00   
27              Monako    EUR                      200.00   
28             Nemčija    EUR                      500.00   
29          Nizozemska    EUR                      300.00   
30            Norveška    NOK                      546.00   
31             Poljska    PLN                     1150.00   
32         Portugalska    EUR                      250.00   
33            Romunija    RON                      261.00   
34              Rusija    RUB                       50.00   
35  Severna Makedonija    MKD                      244.80   
36            Slovaška    EUR                      200.00   
37           Slovenija    EUR                      300.00   
38             Španija    EUR                      500.00   
39              Srbija    RSD                       45.00   
40             Švedska    SEK                        0.00   
41               Švica    CHF                      640.20   
42             Turčija    TRY                       27.05   
43            Ukrajina    UAH                       56.10   
44        V. Britanija    GBP                     5990.00   

    Min kazni za prehitro vožnjo (EUR)  Min kazni za varnostni pas (EUR)  \
0                                20.00                             50.00   
1                                24.00                             20.00   
2                                35.00                             35.00   
3                               160.00                            116.00   
4                                 6.88                              6.88   
5                                25.55                             51.10   
6                                10.22                             25.55   
7                                97.50                             58.50   
8                                60.00                             40.00   
9                               469.00                            201.00   
10                              120.00                            200.00   
11                              200.00                             70.00   
12                              135.00                            135.00   
13                                0.00                              0.00   
14                              100.00                            350

## Analiza .csv datoteke s sortiranimi cenami

Za še lažjo predstavo spodnja tabela prikaže države urejene po ceni kazni za neuporabo varnostnega pasu padajoče (seveda vse v EUR).

In [15]:
sortirano_tabela = pd.read_csv("kazni_evropske_drzave_eur_sortirano.csv")
sortirano_tabela

Država Valuta  Min kazni za alkohol (EUR)  \
0         V. Britanija    GBP                     5990.00   
1               Grčija    EUR                       78.00   
2               Danska    DKK                        0.00   
3             Estonija    EUR                      400.00   
4              Španija    EUR                      500.00   
5           Nizozemska    EUR                      300.00   
6             Francija    EUR                      135.00   
7              Švedska    SEK                        0.00   
8              Hrvaška    EUR                       90.00   
9             Norveška    NOK                      546.00   
10               Irska    EUR                     5000.00   
11         Portugalska    EUR                      250.00   
12           Slovenija    EUR                      300.00   
13             Belgija    EUR                      150.00   
14             Italija    EUR                      532.00   
15              Finska    EUR                        0.00   
16           Islandija    ISK                      490.00   
17       Liechtenstein    CHF                      640.20   
18               Švica    CHF                      640.20   
19               Češka    CZK                       97.50   
20            Romunija    RON                      261.00   
21                 BIH    BAM                       25.55   
22            Albanija    ALL                       50.00   
23          Luksemburg    EUR                      145.00   
24               Malta    EUR                     1200.00   
25              Srbija    RSD                       45.00   
26           Črna Gora    EUR                       70.00   
27           Moldavija    MDL                      390.00   
28            Avstrija    EUR                      300.00   
29              Kosovo    EUR                       65.00   
30             Latvija    EUR                      210.00   
31               Litva    EUR                      289.00   
32             Nemčija    EUR                      500.00   
33           Bolgarija    BGN                      255.50   
34             Poljska    PLN                     1150.00   
35              Monako    EUR                      200.00   
36              Andora    EUR                      600.00   
37           Madžarska    HUF                      200.00   
38  Severna Makedonija    MKD                      244.80   
39            Slovaška    EUR                      200.00   
40              Rusija    RUB                       50.00   
41          Belorusija    BYN                      344.23   
42             Turčija    TRY                       27.05   
43            Ukrajina    UAH                       56.10   
44           Gibraltar    GBP                        0.00   

    Min kazni za prehitro vožnjo (EUR)  Min kazni za varnostni pas (EUR)  \
0                              1198.00                           1198.00   
1                               100.00                            350.00   
2                               469.00                            201.00   
3                               120.00                            200.00   
4                               100.00                            200.00   
5                               240.00                            180.00   
6                               135.00                            135.00   
7                               243.60                            130.50   
8                               130.00                            130.00   
9                               655.20                            126.00   
10                              160.00                            120.00   
11                               60.00                            120.00   
12                              120.00                            120.00   
13                              160.00                            116.00   
14                              169.00                             80